// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DatabaseFirst.Models.Configurations;
using DatabaseFirst.TestModels;
using DatabaseFirst.TestModels.dboSchema;
using DatabaseFirst.TestModels.LibrarySchema;
using DatabaseFirst.TestModels.ManagementSchema;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
#nullable enable

namespace DatabaseFirst.Models;

public partial class CityLibraryDbContext : DbContext
{
    public CityLibraryDbContext()
    {
    }

    public CityLibraryDbContext(DbContextOptions<CityLibraryDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Author> Authors { get; set; }

    public virtual DbSet<AuthorsBook> AuthorsBooks { get; set; }

    public virtual DbSet<Book> Books { get; set; }

    public virtual DbSet<BookCopy> BookCopies { get; set; }

    public virtual DbSet<BooksAuthor> BooksAuthors { get; set; }

    public virtual DbSet<BorrowTransaction> BorrowTransactions { get; set; }

    public virtual DbSet<Branch> Branches { get; set; }

    public virtual DbSet<Fine> Fines { get; set; }

    public virtual DbSet<Librarian> Librarians { get; set; }

    public virtual DbSet<Member> Members { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=CityLibraryDb;Integrated Security=True;TrustServerCertificate=true;");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.AuthorConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.AuthorsBookConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.BookConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.BookCopyConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.BooksAuthorConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.BorrowTransactionConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.BranchConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.FineConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.LibrarianConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.MemberConfiguration());

        OnModelCreatingPartial(modelBuilder);

        modelBuilder.Entity<AuthorBooks>(entity =>
        {
            entity.HasNoKey();     
            entity.ToTable((string)null);  // not mapped to any table
        });
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
