// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DatabaseFirst.Models;
using DatabaseFirst.TestModels;
using DatabaseFirst.TestModels.dboSchema;
using DatabaseFirst.TestModels.LibrarySchema;
using DatabaseFirst.TestModels.ManagementSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace DatabaseFirst.Models.Configurations
{
    public partial class AuthorConfiguration : IEntityTypeConfiguration<Author>
    {
        public void Configure(EntityTypeBuilder<Author> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Authors__3214EC0785D88615");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Author> entity);
    }
}
