// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DatabaseFirst.Models;
using DatabaseFirst.TestModels;
using DatabaseFirst.TestModels.dboSchema;
using DatabaseFirst.TestModels.LibrarySchema;
using DatabaseFirst.TestModels.ManagementSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace DatabaseFirst.Models.Configurations
{
    public partial class BooksAuthorConfiguration : IEntityTypeConfiguration<BooksAuthor>
    {
        public void Configure(EntityTypeBuilder<BooksAuthor> entity)
        {
            entity.HasKey(e => new { e.BookIsbn, e.AuthorId }).HasName("PK__Books_Au__69D776C8A41B1C2A");

            entity.HasOne(d => d.Author).WithMany(p => p.BooksAuthors)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BA_Author");

            entity.HasOne(d => d.BookIsbnNavigation).WithMany(p => p.BooksAuthors)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BA_Book");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BooksAuthor> entity);
    }
}
