// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DatabaseFirst.Models;
using DatabaseFirst.TestModels;
using DatabaseFirst.TestModels.dboSchema;
using DatabaseFirst.TestModels.LibrarySchema;
using DatabaseFirst.TestModels.ManagementSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace DatabaseFirst.Models.Configurations
{
    public partial class BookCopyConfiguration : IEntityTypeConfiguration<BookCopy>
    {
        public void Configure(EntityTypeBuilder<BookCopy> entity)
        {
            entity.HasKey(e => e.CopyId).HasName("PK__BookCopi__C26CCCC544609DF6");

            entity.Property(e => e.CurrentStatus)
                .HasDefaultValue("Available")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_CurrentStatus");

            entity.HasOne(d => d.BookIsbnNavigation).WithMany(p => p.BookCopies).HasConstraintName("FK_Copy_Book");

            entity.HasOne(d => d.Branch).WithMany(p => p.BookCopies).HasConstraintName("FK_Copy_Branch");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BookCopy> entity);
    }
}
