// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DatabaseFirst.Models;
using DatabaseFirst.TestModels;
using DatabaseFirst.TestModels.dboSchema;
using DatabaseFirst.TestModels.LibrarySchema;
using DatabaseFirst.TestModels.ManagementSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace DatabaseFirst.Models.Configurations
{
    public partial class BranchConfiguration : IEntityTypeConfiguration<Branch>
    {
        public void Configure(EntityTypeBuilder<Branch> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Branches__3214EC0736C7D3BF");

            entity.HasOne(d => d.Manager).WithOne(p => p.Branch).HasConstraintName("FK__Branches__Manage__3A81B327");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Branch> entity);
    }
}
