// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DatabaseFirst.Models;
using DatabaseFirst.TestModels;
using DatabaseFirst.TestModels.dboSchema;
using DatabaseFirst.TestModels.LibrarySchema;
using DatabaseFirst.TestModels.ManagementSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace DatabaseFirst.Models.Configurations
{
    public partial class FineConfiguration : IEntityTypeConfiguration<Fine>
    {
        public void Configure(EntityTypeBuilder<Fine> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Fines__3214EC07AC04D47B");

            entity.HasOne(d => d.BorrowTran).WithOne(p => p.Fine).HasConstraintName("FK_FineTran");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Fine> entity);
    }
}
