// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DatabaseFirst.Models;
using DatabaseFirst.TestModels;
using DatabaseFirst.TestModels.dboSchema;
using DatabaseFirst.TestModels.LibrarySchema;
using DatabaseFirst.TestModels.ManagementSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace DatabaseFirst.Models.Configurations
{
    public partial class LibrarianConfiguration : IEntityTypeConfiguration<Librarian>
    {
        public void Configure(EntityTypeBuilder<Librarian> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Libraria__3214EC0737786BE0");

            entity.Property(e => e.Id).ValueGeneratedNever();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Librarian> entity);
    }
}
