// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DatabaseFirst.Models;
using DatabaseFirst.TestModels;
using DatabaseFirst.TestModels.dboSchema;
using DatabaseFirst.TestModels.LibrarySchema;
using DatabaseFirst.TestModels.ManagementSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace DatabaseFirst.Models.Configurations
{
    public partial class MemberConfiguration : IEntityTypeConfiguration<Member>
    {
        public void Configure(EntityTypeBuilder<Member> entity)
        {
            entity.HasKey(e => e.MembershipId).HasName("PK__Members__92A786791E71E3FE");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Member> entity);
    }
}
